#docker-compose up -d
version: "3"

services:
  postgres:
    image: docker.io/library/postgres:15
    container_name: data_lab_postgres
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    networks:
      - data-net

  airflow:
    image: apache/airflow:2.7.1
    container_name: data_lab_airflow
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__EXECUTOR: 'SequentialExecutor'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://data:data@postgres:5432/warehouse'
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres
    networks:
      - data-net

  devcontainer:
    image: docker.io/library/python:3.11-slim
    container_name: data_lab_devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    working_dir: /workspace
    networks:
      - data-net
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
      - airflow
    stdin_open: true
    tty: true

networks:
  data-net: